name: Running the CI for testing the hello world     
on: 
  push:
    branches:
      - ci-branch
  pull_request:
    branches:
      - ci-branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world echo 
        run: echo "Hello, world! from code-branch"